---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.18.2
    hooks:
      - id: stylua

  - repo: https://github.com/lunarmodules/luacheck
    rev: v1.1.0
    hooks:
      - id: luacheck

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.6.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.8.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

  - repo: local
    hooks:
      - id: generate-api-docs
        name: Generate API documentation
        entry: lua scripts/generate-api-docs.lua
        language: system
        files: '^lua/.*\.lua$'
        pass_filenames: false
