name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: '5.1'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          luarocks install luacheck
          luarocks install busted
          luarocks install luassert
      - name: Lint with luacheck
        run: luacheck lua/ plugin/ tests/
      - name: Format check with stylua
        uses: JohnnyMorganz/stylua-action@v3
        with:
          version: latest
          args: --check lua/ plugin/ tests/
      - name: Run tests
        run: busted tests/
